server:
  port: 8888

spring:
  application:
    name: pet-helper-config-service
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
  profiles:
    active: native
