server:
  port: 8084

chat-scheduler:
  cron-expression: "0 * * * * ?"
  period: 10

spring:
  application:
    name: pet-helper-message-service
  redis:
    port: 6379
    host: localhost
    cluster:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/messages?stringtype=unspecified
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  auth-service:
    value: authService
    url: http://localhost:8080/api/v1/auth
  user-service:
    value: userService
    url: http://localhost:8081/api/v1/users
  image-service:
    value: imageService
    url: http://localhost:8080/api/v1