server:
  port: 8083

spring:
  application:
    name: pet-helper-admin-service

user-scheduler:
  cron-expression: "0 * * * * ?"
  year-period: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  auth-service:
    value: authService
    url: http://localhost:8080/api/v1/auth
  user-service:
    value: userService
    url: http://localhost:8081/api/v1/users