server:
  port: 8081

spring:
  application:
    name: pet-helper-user-service
  redis:
    port: 6379
    host: localhost
    cluster:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Users
      uri: mongodb://root:root@localhost:27017/Users?authSource=admin&retryWrites=true&w=majority

feign:
  client:
    config:
      readTimeout: 160000000
  pet-helper-service:
    value: petHelperService
    url: http://localhost:8080/api/v1
  message-service:
    value: messageService
    url: http://localhost:8080/api/v1/chats

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka