server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: pet-helper-api-gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka