# --- own parameters ---
app:
  database:
    name: images
    username: root
    password: root
    ddl: update
  doc:
    path: /api/doc/
  file-storage:
    path: /Users/vitmvit/bin/projects/graduation-project/file_storage
    deep: 3
# --- service parameters ---
server:
  port: 8086
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB