server:
  port: 8085

spring:
  application:
    name: pet-helper-service
  redis:
    port: 6379
    host: localhost
    cluster:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/records_test?stringtype=unspecified
    url: jdbc:postgresql://localhost:5432/records?stringtype=unspecified
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
#  client:
  #    config:
  #      readTimeout: 160000000
  auth-service:
    value: authService
    url: http://localhost:8080/api/v1/auth
  image-service:
    value: imageService
    url: http://localhost:8080/api/v1/
  tag-service:
    value: authService
    url: http://localhost:8080/api/v1/tags
  article-service:
    value: userService
    url: http://localhost:8080/api/v1/articles
  user-service:
    value: userService
    url: http://localhost:8081/api/v1/users
